default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: matic
  password: "Nogomet2015!"
  host: 78.47.245.88

development:
  <<: *default
  database: pgd_trnava_development

test:
  <<: *default
  database: pgd_trnava_test

production:
  <<: *default
  database: pgd_trnava_development

  queue:
    <<: *default
    database: pgd_trnava_development
